services:
  api:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    ports:
      - "8000:8000"
    volumes:
      - ./api-gateway:/app

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "8001:8001"
    volumes:
      - ./auth-service:/app
    depends_on:
      - user-service

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "8002:8002"
    volumes:
      - ./user-service:/app

  reservation-service:
    build:
      context: ./reservation-service
      dockerfile: Dockerfile
    container_name: reservation_service
    ports:
      - "8003:8003"
    volumes:
      - ./reservation-service:/app

  paiement-service:
    build:
      context: ./paiement-service
      dockerfile: Dockerfile
    container_name: paiement_service
    ports:
      - "8004:8004"
    volumes:
      - ./paiement-service:/app

  test:
    build:
      context: ./${TEST_SERVICE:-api-gateway}
      dockerfile: Dockerfile.test
    container_name: microservices_tests
    volumes:
      - ./${TEST_SERVICE:-api-gateway}:/app
      - ./htmlcov:/app/htmlcov
    environment:
      - PYTHONPATH=/app
