FROM python:3.13-slim

WORKDIR /app

RUN pip install --no-cache-dir poetry

COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false && poetry install --no-root

COPY . .

RUN poetry install --only-root

CMD ["poetry", "run", "pytest", "-v", "--cov=src", "--cov-report=term-missing", "--cov-report=html", "--cov-fail-under=80"]
